### ISSUE TITLE
AlpineLinux Compiling TheDarkMod Error

### ISSUE THREAD

**Issue by sodomon2** [fholger/thedarkmod#11]
**Hello very good I have 
I've got a compilation error and here's the error.**

**and well this same error I have with the official version of thedarkmod will be some error of my system?**

framework/minizip/unzip.cpp:110:19: error: 'time_t' does not name a type; did you mean 'size_t'?
 #define ID_TIME_T time_t
                   ^~~~~~
include/../sys/sys_public.h:391:1: note: in expansion of macro 'ID_TIME_T'
 ID_TIME_T  Sys_FileTimeStamp( FILE *fp );
 ^~~~~~~~~
framework/minizip/unzip.cpp:110:19: error: 'time_t' does not name a type; did you mean 'size_t'?
 #define ID_TIME_T time_t
                   ^~~~~~
include/../sys/sys_public.h:392:1: note: in expansion of macro 'ID_TIME_T'
 ID_TIME_T       Sys_DosToUnixTime( unsigned long dostime );
 ^~~~~~~~~
framework/minizip/unzip.cpp:110:19: error: 'time_t' was not declared in this scope
 #define ID_TIME_T time_t
                   ^~~~~~
include/../sys/sys_public.h:394:34: note: in expansion of macro 'ID_TIME_T'
 const char * Sys_TimeStampToStr( ID_TIME_T timeStamp );
                                  ^~~~~~~~~
framework/minizip/unzip.cpp:110:19: note: suggested alternative: 'size_t'
 #define ID_TIME_T time_t
                   ^~~~~~
include/../sys/sys_public.h:394:34: note: in expansion of macro 'ID_TIME_T'
 const char * Sys_TimeStampToStr( ID_TIME_T timeStamp );
                                  ^~~~~~~~~
scons: *** [build/scons_x64/release/core/framework/minizip/unzip.o] Error 1
scons: building terminated because of errors.
 
**and this is the error of the original**

framework/minizip/unzip.cpp:110:19: error: 'time_t' does not name a type; did you mean 'size_t'?
 #define ID_TIME_T time_t
                   ^~~~~~
include/../sys/sys_public.h:389:1: note: in expansion of macro 'ID_TIME_T'
 ID_TIME_T  Sys_FileTimeStamp( FILE *fp );
 ^~~~~~~~~
framework/minizip/unzip.cpp:110:19: error: 'time_t' does not name a type; did you mean 'size_t'?
 #define ID_TIME_T time_t
                   ^~~~~~
include/../sys/sys_public.h:390:1: note: in expansion of macro 'ID_TIME_T'
 ID_TIME_T       Sys_DosToUnixTime( unsigned long dostime );
 ^~~~~~~~~
framework/minizip/unzip.cpp:110:19: error: 'time_t' was not declared in this scope
 #define ID_TIME_T time_t
                   ^~~~~~
include/../sys/sys_public.h:392:34: note: in expansion of macro 'ID_TIME_T'
 const char * Sys_TimeStampToStr( ID_TIME_T timeStamp );
                                  ^~~~~~~~~
framework/minizip/unzip.cpp:110:19: note: suggested alternative: 'size_t'
 #define ID_TIME_T time_t
                   ^~~~~~
include/../sys/sys_public.h:392:34: note: in expansion of macro 'ID_TIME_T'
 const char * Sys_TimeStampToStr( ID_TIME_T timeStamp );
                                  ^~~~~~~~~
framework/minizip/zip.cpp:52:19: error: 'time_t' does not name a type; did you mean 'size_t'?
 #define ID_TIME_T time_t
                   ^~~~~~
include/../sys/sys_public.h:389:1: note: in expansion of macro 'ID_TIME_T'
 ID_TIME_T  Sys_FileTimeStamp( FILE *fp );
 ^~~~~~~~~
framework/minizip/zip.cpp:52:19: error: 'time_t' does not name a type; did you mean 'size_t'?
 #define ID_TIME_T time_t
                   ^~~~~~
include/../sys/sys_public.h:390:1: note: in expansion of macro 'ID_TIME_T'
 ID_TIME_T       Sys_DosToUnixTime( unsigned long dostime );
 ^~~~~~~~~
framework/minizip/zip.cpp:52:19: error: 'time_t' was not declared in this scope
 #define ID_TIME_T time_t
                   ^~~~~~
include/../sys/sys_public.h:392:34: note: in expansion of macro 'ID_TIME_T'
 const char * Sys_TimeStampToStr( ID_TIME_T timeStamp );

**Comment by fholger** [comment]
You could try if an explicit `#include <ctime>` in the affected files fixes it. However, this error should be reported and fixed upstream, either go to the forums (http://forums.thedarkmod.com) or to the bugtracker (https://bugs.thedarkmod.com).

**Comment by sodomon2** [comment]
it seems that with this #include <ctime> no longer gives me the previous error but now gives me another here the error

tools/compilers/roqvq/codec.cpp:217:6: warning: this 'if' clause does not guard... [-Wmisleading-indentation]
      if (fy<0) fy = 0; if (fy>255) fy = 255;
      ^~
tools/compilers/roqvq/codec.cpp:217:24: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'if'
      if (fy<0) fy = 0; if (fy>255) fy = 255;
                        ^~
tools/compilers/roqvq/codec.cpp: In member function 'int codec::BestCodeword(unsigned char*, int, double**)':
tools/compilers/roqvq/codec.cpp:22:29: error: '_HUGE_ENUF' was not declared in this scope
 #define INFINITY   ((float)(_HUGE_ENUF * _HUGE_ENUF))
                             ^~~~~~~~~~
/usr/include/math.h:23:28: note: in expansion of macro 'INFINITY'
 #define HUGE_VAL  ((double)INFINITY)
                            ^~~~~~~~
tools/compilers/roqvq/codec.cpp:22:29: note: suggested alternative: 'HUGE_VALF'
 #define INFINITY   ((float)(_HUGE_ENUF * _HUGE_ENUF))
                             ^~~~~~~~~~
/usr/include/math.h:23:28: note: in expansion of macro 'INFINITY'
 #define HUGE_VAL  ((double)INFINITY)
                            ^~~~~~~~
tools/compilers/roqvq/codec.cpp: In member function 'void codec::SparseEncode()':
tools/compilers/roqvq/codec.cpp:1311:5: warning: this 'if' clause does not guard... [-Wmisleading-indentation]
     if (qStatus[i].status < DEAD) num[qStatus[i].status]++; j++;
     ^~
tools/compilers/roqvq/codec.cpp:1311:61: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'if'
     if (qStatus[i].status < DEAD) num[qStatus[i].status]++; j++;
                                                             ^
tools/compilers/roqvq/codec.cpp:1319:5: warning: this 'if' clause does not guard... [-Wmisleading-indentation]
     if (qStatus[i].status < DEAD) num[qStatus[i].status]++; j++;
     ^~
tools/compilers/roqvq/codec.cpp:1319:61: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'if'
     if (qStatus[i].status < DEAD) num[qStatus[i].status]++; j++;
                                                             ^
tools/compilers/roqvq/codec.cpp: In member function 'void codec::EncodeNothing()':
tools/compilers/roqvq/codec.cpp:1412:5: warning: this 'if' clause does not guard... [-Wmisleading-indentation]
     if (qStatus[i].status < DEAD) num[qStatus[i].status]++; j++;
     ^~
tools/compilers/roqvq/codec.cpp:1412:61: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'if'
     if (qStatus[i].status < DEAD) num[qStatus[i].status]++; j++;
                                                             ^
tools/compilers/roqvq/codec.cpp:1420:5: warning: this 'if' clause does not guard... [-Wmisleading-indentation]
     if (qStatus[i].status < DEAD) num[qStatus[i].status]++; j++;
     ^~
tools/compilers/roqvq/codec.cpp:1420:61: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'if'
     if (qStatus[i].status < DEAD) num[qStatus[i].status]++; j++;
                                                             ^
tools/compilers/roqvq/codec.cpp: In member function 'void codec::VQ(int, int, const unsigned char*, float*, double**, bool)':
tools/compilers/roqvq/codec.cpp:22:29: error: '_HUGE_ENUF' was not declared in this scope
 #define INFINITY   ((float)(_HUGE_ENUF * _HUGE_ENUF))
                             ^~~~~~~~~~
/usr/include/math.h:23:28: note: in expansion of macro 'INFINITY'
 #define HUGE_VAL  ((double)INFINITY)
                            ^~~~~~~~
tools/compilers/roqvq/codec.cpp:22:29: note: suggested alternative: 'HUGE_VALF'
 #define INFINITY   ((float)(_HUGE_ENUF * _HUGE_ENUF))
                             ^~~~~~~~~~
/usr/include/math.h:23:28: note: in expansion of macro 'INFINITY'
 #define HUGE_VAL  ((double)INFINITY)
                            ^~~~~~~~
scons: *** [build/scons_x64/release/core/tools/compilers/roqvq/codec.o] Error 1
scons: building terminated because of errors.

**Comment by fholger** [comment]
Like I said, please report it in the TDM forums or the issue tracker.

**Comment by sodomon2** [comment]
ok
