### ISSUE TITLE
distributing darkmod.cfg with broken settings

### ISSUE THREAD

**Issue by addeps3** [fholger/thedarkmod#4]
Hi,
I've spent 20 minutes now trying to locate the Surround Sound setting in darkmod.cfg, which really wasn't necessary because I played around with Surround Sound settings in game menu and the game became unbootable.
After spending whatever time to locate whatever setting in Darkmod.cfg and reverting the number of speakers I managed to revert my problem.
It's really unnecessary to make users go through all this just because they changed from 5.1 to 7.1 in-game.

**Comment by fholger** [comment]
Please submit bug reports to the official bugtracker at http://bugs.thedarkmod.com
This is just a personal playground for my own experiments with the engine. I'm not part of the team and can't help you, sorry.
